version: '3.7'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "2379:2379"
    volumes:
      - etcd-data:/etcd-data
    command: [
      "/usr/local/bin/etcd",
      "--name", "s1",
      "--data-dir", "/etcd-data",
      "--advertise-client-urls", "http://localhost:2379",
      "--listen-client-urls", "http://0.0.0.0:2379"
    ]

volumes:
  etcd-data: